environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    TWINE_USERNAME: bmatthieu3
  # Note: TWINE_PASSWORD is set in Appveyor settings
  matrix:
    # Nightly 64-bit MSVC
    - channel: nightly
      target: x86_64-pc-windows-msvc
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      CIBW_SKIP: "*win32* cp33-* cp34-* cp35-* cp36-* cp37-*"
      CIBW_BEFORE_BUILD: pip install setuptools-rust
    # Nightly 32-bit MSVC
    - channel: nightly
      target: i686-pc-windows-msvc
      PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x" # currently 3.6.5
      PYTHON_ARCH: "32"
      CIBW_SKIP: "*win_amd64* cp33-*"
      CIBW_BEFORE_BUILD: pip install setuptools-rust

# from: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - pip install cibuildwheel==0.9.1 setuptools_rust

build_script:
  - cibuildwheel --output-dir dist
  # Run some tests
  - set PATH=%PYTHON%;%PATH%
  - python -m pip install pytest cffi
  - python setup.py build_rust
  - xcopy "build\lib\rust_pypi\*.pyd" rust_pypi /sy
  - python -m pytest -v rust_pypi
  # Upload to PyPI if the tests succeed
  - python -m pip install twine
  - python -m twine upload \"dist\\*.whl\" --skip-existing

artifacts:
  - path: "dist\\*.whl"
    name: Wheels